vroom vroom

diff --git a/.github/workflows/test-examples.yml b/.github/workflows/test-examples.yml
--- a/.github/workflows/test-examples.yml
+++ b/.github/workflows/test-examples.yml
@@ -38,14 +38,43 @@ jobs:
       - name: "Go to each example and try to build it"
         run: |
           pushd examples
-          for d in *
-          do
-            test -d "$d" || continue
-            pushd "$d"
+          testBuildAndDev(){
             pnpm build
             rm -rf .plasmo
             rm -rf build
             timeout 10 pnpm dev || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi 
+          }
+          # initialize a semaphore with a given number of tokens
+          open_sem(){
+              mkfifo pipe-$$
+              exec 3<>pipe-$$
+              rm pipe-$$
+              local i=$1
+              for((;i>0;i--)); do
+                  printf %s 000 >&3
+              done
+          }
+
+          # run the given command asynchronously and pop/push tokens
+          run_with_lock(){
+              local x
+              # this read waits until there is something to read
+              read -u 3 -n 3 x && ((0==x)) || exit $x
+              (
+              ( "$@"; )
+              # push the return code of the command to the semaphore
+              printf '%.3d' $? >&3
+              )&
+          }
+
+          N=4
+          open_sem $N
+
+          for d in *;
+          do
+            test -d "$d" || continue
+            pushd "$d"
+            run_with_lock testBuildAndDev
             popd
           done
           popd
